//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pool")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u32,
    pub owner_id: u32,
    pub bet_unit: u32,
    pub brokerage_ratio: i64,
    pub brokerage: i64,
    pub pot_ratio: i64,
    pub pot: i64,
    pub suction: i64,
    pub base_line: i64,
    pub boundary: i64,
    pub bonus: i64,
    pub jackpot: i64,
    pub advance: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
